//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class calldetail
    {
        public int idcalldetail { get; set; }
        public int idcallhistory2 { get; set; }
        public int detailnum { get; set; }
        public Nullable<int> parentdetailnum { get; set; }
        public string dest_num { get; set; }
        public int specdsttype { get; set; }
        public System.DateTime starttime { get; set; }
        public System.TimeSpan dur { get; set; }
        public Nullable<System.DateTime> answertime { get; set; }
        public int status { get; set; }
        public bool is_compl { get; set; }
        public bool is_tooutside { get; set; }
        public string dest_dn { get; set; }
        public string otherparty { get; set; }
        public string billprefix { get; set; }
        public string billratename { get; set; }
        public Nullable<decimal> billrate { get; set; }
        public Nullable<decimal> billcost { get; set; }
    
        public virtual callhistory3 callhistory3 { get; set; }
    }
}
