//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class callcent_ag_queuestatus
    {
        public int idcallcent_ag_queuestatus { get; set; }
        public string q_num { get; set; }
        public string ag_num { get; set; }
        public System.DateTime timeofupdate { get; set; }
        public Nullable<bool> is_loggedin_in_queue { get; set; }
        public Nullable<bool> is_loggedin_in_allqueues { get; set; }
    }
}
