//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class callhistory3
    {
        public callhistory3()
        {
            this.calldetails = new HashSet<calldetail>();
        }
    
        public int idcallhistory3 { get; set; }
        public string callid { get; set; }
        public System.DateTime starttime { get; set; }
        public Nullable<System.DateTime> answertime { get; set; }
        public System.DateTime endtime { get; set; }
        public System.TimeSpan duration { get; set; }
        public bool is_answ { get; set; }
        public bool is_fail { get; set; }
        public bool is_compl { get; set; }
        public Nullable<bool> is_fromoutside { get; set; }
        public Nullable<int> mediatype { get; set; }
        public string from_no { get; set; }
        public string to_no { get; set; }
        public string callerid { get; set; }
        public string dialednumber { get; set; }
        public string lastcallerid { get; set; }
        public string lastdialednumber { get; set; }
        public string group_no { get; set; }
        public string line_no { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> totalcost { get; set; }
        public string billprefix { get; set; }
        public string billratename { get; set; }
        public Nullable<int> grpanswdetail { get; set; }
        public string recfile { get; set; }
        public string callchain { get; set; }
        public bool is_visible { get; set; }
        public string caller_display_name { get; set; }
    
        public virtual ICollection<calldetail> calldetails { get; set; }
    }
}
