//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class callcent_ag_dropped_calls
    {
        public int idcallcent_ag_dropped_calls { get; set; }
        public string q_num { get; set; }
        public string ag_num { get; set; }
        public System.DateTime time_start { get; set; }
        public System.DateTime time_end { get; set; }
        public int reason_noanswercode { get; set; }
        public string reason_noanswerdesc { get; set; }
        public string call_history_id { get; set; }
        public string q_call_history_id { get; set; }
    }
}
