//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class callcent_queuecalls
    {
        public int idcallcent_queuecalls { get; set; }
        public string q_num { get; set; }
        public System.DateTime time_start { get; set; }
        public System.DateTime time_end { get; set; }
        public Nullable<System.TimeSpan> ts_waiting { get; set; }
        public Nullable<System.TimeSpan> ts_polling { get; set; }
        public Nullable<System.TimeSpan> ts_servicing { get; set; }
        public Nullable<System.TimeSpan> ts_locating { get; set; }
        public int count_polls { get; set; }
        public int count_dialed { get; set; }
        public int count_rejected { get; set; }
        public int count_dials_timed { get; set; }
        public int reason_noanswercode { get; set; }
        public int reason_failcode { get; set; }
        public string reason_noanswerdesc { get; set; }
        public string reason_faildesc { get; set; }
        public string call_history_id { get; set; }
        public string q_cal { get; set; }
        public string from_userpart { get; set; }
        public string from_displayname { get; set; }
        public string to_dialednum { get; set; }
        public string to_dn { get; set; }
        public int to_dntype { get; set; }
        public string cb_num { get; set; }
        public string call_result { get; set; }
        public int deal_status { get; set; }
        public bool is_visible { get; set; }
    }
}
