//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_history_mess
    {
        public int id_chat_history { get; set; }
        public string from_no { get; set; }
        public string from_name { get; set; }
        public System.DateTime time_received { get; set; }
        public string message { get; set; }
        public string party { get; set; }
    }
}
