//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class extension
    {
        public extension()
        {
            this.Dept2ext = new HashSet<Dept2ext>();
            this.group2ext = new HashSet<group2ext>();
        }
    
        public int idextension { get; set; }
        public int fkiddn { get; set; }
        public string authid { get; set; }
        public string authpswd { get; set; }
        public string outcid { get; set; }
        public bool recrdout { get; set; }
        public bool recrdin { get; set; }
        public bool accstatus { get; set; }
        public bool accconfig { get; set; }
        public Nullable<int> noanswtimeout { get; set; }
        public Nullable<int> busydetection { get; set; }
        public bool isinternal { get; set; }
        public bool isbindtoms { get; set; }
        public bool issupportreinvite { get; set; }
        public bool issupportreplaces { get; set; }
        public int castatus { get; set; }
        public int qstatus { get; set; }
        public bool enabled { get; set; }
        public bool use_srtp { get; set; }
        public bool hidepresence { get; set; }
        public Nullable<int> currentprofile { get; set; }
        public Nullable<int> overrideprofile { get; set; }
        public Nullable<int> fallbackprofile { get; set; }
    
        public virtual ICollection<Dept2ext> Dept2ext { get; set; }
        public virtual ICollection<group2ext> group2ext { get; set; }
    }
}
