//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.group2ext = new HashSet<group2ext>();
        }
    
        public int idgroup { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<group2ext> group2ext { get; set; }
    }
}
