//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class group2ext
    {
        public int id { get; set; }
        public int fkidGroup { get; set; }
        public int fkidextension { get; set; }
    
        public virtual extension extension { get; set; }
        public virtual group group { get; set; }
    }
}
