//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class queue
    {
        public int idqueue { get; set; }
        public int fkiddn { get; set; }
        public Nullable<int> fknoanswerdn { get; set; }
        public int noanswertype { get; set; }
        public string noanswertoout { get; set; }
        public string name { get; set; }
        public Nullable<bool> enableintro { get; set; }
        public string introfile { get; set; }
        public bool enablesm { get; set; }
        public int smtimeout { get; set; }
        public string onholdfile { get; set; }
        public int mastertimeout { get; set; }
        public int ringtime { get; set; }
        public string cidprefix { get; set; }
        public Nullable<int> pollingstrategy { get; set; }
    }
}
