//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayOnlineReportApplication.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReservesEntities : DbContext
    {
        public ReservesEntities()
            : base("name=ReservesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> sp_rpt_AdminLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_rpt_AdminLogin", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_rpt_GetAccountInfo_Result> sp_rpt_GetAccountInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rpt_GetAccountInfo_Result>("sp_rpt_GetAccountInfo");
        }
    
        public virtual ObjectResult<string> sp_rpt_GetPaymentStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_rpt_GetPaymentStatus");
        }
    }
}
