//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.BAL.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAF.BAL.ResourceFile.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgentLog.
        /// </summary>
        public static string AgentLogReportName {
            get {
                return ResourceManager.GetString("AgentLogReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgentLogWithSummary.
        /// </summary>
        public static string AgentLogWithSummaryReportName {
            get {
                return ResourceManager.GetString("AgentLogWithSummaryReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerZoneBigScreen1.
        /// </summary>
        public static string BigScreenZone1Name {
            get {
                return ResourceManager.GetString("BigScreenZone1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerZoneBigScreen2.
        /// </summary>
        public static string BigScreenZone2Name {
            get {
                return ResourceManager.GetString("BigScreenZone2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatLog.
        /// </summary>
        public static string ChatLogReportName {
            get {
                return ResourceManager.GetString("ChatLogReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectionReport.
        /// </summary>
        public static string CollectionReportName {
            get {
                return ResourceManager.GetString("CollectionReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNDStatusReport.
        /// </summary>
        public static string DNDStatusReportName {
            get {
                return ResourceManager.GetString("DNDStatusReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropCalls.
        /// </summary>
        public static string DropCallLogReportName {
            get {
                return ResourceManager.GetString("DropCallLogReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HourlyCallReport.
        /// </summary>
        public static string HourlyCallReportName {
            get {
                return ResourceManager.GetString("HourlyCallReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerZoneBig.
        /// </summary>
        public static string PowerZoneBigScreen {
            get {
                return ResourceManager.GetString("PowerZoneBigScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerZone.
        /// </summary>
        public static string PowerZoneReportName {
            get {
                return ResourceManager.GetString("PowerZoneReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueueLog.
        /// </summary>
        public static string QueueLogReportName {
            get {
                return ResourceManager.GetString("QueueLogReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied to directory..
        /// </summary>
        public static string RecordingPathAccessDenied {
            get {
                return ResourceManager.GetString("RecordingPathAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in updating recording path..
        /// </summary>
        public static string RecordingPathError {
            get {
                return ResourceManager.GetString("RecordingPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exists..
        /// </summary>
        public static string RecordingPathInvalid {
            get {
                return ResourceManager.GetString("RecordingPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording path updated successfully..
        /// </summary>
        public static string RecordingPathSuccess {
            get {
                return ResourceManager.GetString("RecordingPathSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreCard.
        /// </summary>
        public static string ScoreDateReportName {
            get {
                return ResourceManager.GetString("ScoreDateReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchByPhone.
        /// </summary>
        public static string SearchByPhoneReportName {
            get {
                return ResourceManager.GetString("SearchByPhoneReportName", resourceCulture);
            }
        }
    }
}
